name: Build Dev Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to tag onto Docker image"
        default: "dev"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version
        run: |
          echo ${{ github.event.inputs.version }} > semantic.version
      - name: Build Godot Project
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: TetraForce
          preset: linux
          projectDir: '.'
          debugMode: 'true'
      - name: Get Docker Repo Name
        id: find_repo
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=REPO::$REPO
      - name: Push Tag to GitHub Package
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: "docker.pkg.github.com/${{ steps.find_repo.outputs.REPO }}"
          BUILD_PATH: "."
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "tetraforce"
          TAG_NAME: ${{ github.event.inputs.version }}
          LATEST: "false"